### ISSUE TITLE
mcmf_dfs ne radi dobro

### ISSUE THREAD

**Issue by dbradac** [stjepang/snippets#1]
Kad se pokrene s ovim inputom u formatu
broj nodeova, broj edgeva
za svaki edge: A, B, kapacitet, cijena

mcmf_dfs daje output: flow = 2, cost = -9
mcmf_dijkstra daje output: flow = 2, cost = -18

output od mcmf_dijkstra je tocan

[in.txt](https://github.com/stjepang/snippets/files/573956/in.txt)

**Comment by stjepang** [comment]
va promjena bi trebala riješiti problem: https://github.com/stjepang/snippets/pull/2/files

Možeš li samo provjeriti da `mcmf_dfs` sada zbilja i radi na zadatku na kojem si dobivao WA?
